import { renderToStaticMarkup } from 'react-dom/server';
import { MemoryRouter } from 'react-router-dom';
import { OnlyCoinLists } from '../src/features/onlycoin/OnlyCoinLists';
import type { OnlyCoinDaily } from '../src/shared/types/onlycoin';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { fetchOnlyCoinDaily, fetchOnlyCoinReview, fetchOnlyCoinSource, controlOnlyCoinSource } from '../src/shared/api/onlycoin';
assert.ok(existsSync('src/shared/lib/onlycoin.ts'), 'OnlyCoin server-anchored expiry and scan guard must exist');
import { dailyExpiry, isDailyCurrent, matchingConfirmed } from '../src/shared/lib/onlycoin';
const cycle = { board_key: 'y' as const, business_date: '2026-09-09', cycle_start_utc: '2026-09-09T00:00:00Z', cycle_end_utc: '2026-09-10T00:00:00Z', server_time: '2026-09-09T23:59:50Z' };
const expiry = dailyExpiry(cycle, 1000);
assert.equal(expiry, 11000, 'expiry uses server clock, not client date');
assert.equal(isDailyCurrent(cycle, expiry, 10999), true);
assert.equal(isDailyCurrent(cycle, expiry, 11000), false, 'offline midnight must expire old rows');
assert.equal(dailyExpiry({ ...cycle, server_time: 'broken' }, 1000), 1000);
assert.equal(isDailyCurrent({ ...cycle, business_date: '2026-09-08' }, expiry, 1001), false);
assert.equal(matchingConfirmed({ scan_id: 'old' }, 'new'), null);
assert.deepEqual(matchingConfirmed({ scan_id: 'same' }, 'same'), { scan_id: 'same' });
console.log('PASS OnlyCoin server anchored midnight expiry and confirmed scan guard');
import { onlyCoinReplayTime, onlyCoinLocalTime, onlyCoinCycleEndInput } from '../src/shared/lib/onlycoin';
assert.equal(onlyCoinLocalTime('2026-09-08T08:15'), '2026-09-08T01:15:00Z');
assert.equal(onlyCoinLocalTime('2026-09-09T06:59:59'), '2026-09-08T23:59:59Z');
assert.equal(onlyCoinCycleEndInput('2026-09-08'), '2026-09-09T06:59:59');
assert.equal(onlyCoinReplayTime('2026-09-08', '2026-09-08T07:00'), '2026-09-08T07:00:00Z');
assert.equal(onlyCoinReplayTime('2026-09-08', '2026-09-08T07:00:00'), '2026-09-08T07:00:00Z');
assert.throws(() => onlyCoinReplayTime('2026-09-08', '2026-09-09T07:00'), /同一 UTC/);
assert.throws(() => onlyCoinReplayTime('2026-02-30', '2026-02-30T07:00'), /无效/);
const calls: { url: string; init?: RequestInit }[] = [];
globalThis.fetch = (async (url, init) => { calls.push({ url: String(url), init }); return new Response('{}', { status: 200 }); }) as typeof fetch;
await fetchOnlyCoinDaily(); await fetchOnlyCoinReview('2026-09-09', '2026-09-09T12:00:00Z'); await fetchOnlyCoinSource();
await controlOnlyCoinSource({ enabled: false, expected_revision: 3, request_id: 'test-only', reason: 'test' }, 'memory-only');
assert.equal(calls[0].url, '/api/v1/screener-y/dmr-daily');
assert.equal(new URL(calls[1].url, 'https://test').searchParams.get('as_of'), '2026-09-09T12:00:00Z');
assert.equal(calls[2].url, '/api/v1/onlycoin/sources/screener-y/status');
assert.equal(calls[3].init?.method, 'PUT');
assert.equal(JSON.parse(String(calls[3].init?.body)).expected_revision, 3);
assert.equal((calls[3].init?.headers as Record<string,string>).Authorization, 'Bearer memory-only');
globalThis.fetch = (async () => new Response(JSON.stringify({ error: 'admin unavailable' }), { status: 403 })) as typeof fetch;
await assert.rejects(() => controlOnlyCoinSource({ enabled: true, expected_revision: 3, request_id: 'test', reason: 'test' }, ''), /403.*admin unavailable/);
assert.ok(existsSync('src/features/onlycoin/OnlyCoinPanel.tsx'), 'daily three-column UI must exist');
const screen = readFileSync('src/pages/ScreenerPage.tsx', 'utf8');
assert.match(screen, /matchingConfirmed/);
assert.match(screen, /OnlyCoinPanel/);
assert.match(readFileSync('src/pages/ReviewPage.tsx','utf8'), /OnlyCoinReview/);
const members = Array.from({ length: 15 }, (_, i) => ({ member_id: `member-${i}`, symbol: `COIN${i}USDT`, first_selected_at: cycle.cycle_start_utc, first_available_at: null, first_scan_id: 'first', first_direction: 'LONG', directions: ['LONG','SHORT'], parameter_version: null, rule_identity: null, provenance: 'observed_archive' }));
const fixture: OnlyCoinDaily = { ...cycle, projection_revision: 2, as_of_scan_id: 'first', long: members, short: [], onlycoin: members, counts: { long: 15, short: 0, onlycoin: 15 }, coverage: { complete: false }, stale: true };
const html = renderToStaticMarkup(<MemoryRouter><OnlyCoinLists data={fixture} /></MemoryRouter>);
assert.equal((html.match(/<li/g) || []).length, 31, 'all 15 members in each nonempty list, never slice to six');
assert.ok(html.indexOf('LONG (') < html.indexOf('SHORT (') && html.indexOf('SHORT (') < html.indexOf('OnlyCoin ('));
assert.match(html, /COIN14USDT/); assert.match(html, /observed_archive/); assert.match(html, /数据陈旧/);
const css = readFileSync('src/features/onlycoin/onlycoin.css','utf8');
// Six compact rows: 6*30px + 5*4px gaps = 200px; data is never sliced.
assert.match(css, /max-height:200px/); assert.match(css, /height:30px/); assert.match(css, /overflow-y:auto/);
assert.match(css, /repeat\(3,minmax\(0,1fr\)\)/);
assert.match(html, /onlycoin-time/);
const source = readFileSync('src/features/onlycoin/OnlyCoinSourceControl.tsx','utf8');
assert.doesNotMatch(source, /localStorage|sessionStorage/);
assert.match(source, /type="password"/); assert.match(source, /expected_revision: status.revision/);
assert.match(source, /await controlOnlyCoinSource[\s\S]*await fetchOnlyCoinSource/);
const panel = readFileSync('src/features/onlycoin/OnlyCoinPanel.tsx','utf8');
assert.match(panel, /15000/); assert.match(panel, /visibilitychange/);
assert.match(panel, /wallReceived/, 'sleep/resume needs conservative wall elapsed fallback when performance clock pauses');
console.log('PASS OnlyCoin API, complete-list SSR, scoped UI and source authorization contracts');


