// Run against an isolated or deployed read-only gateway: BASE_URL=... node this-file.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const base = process.env.BASE_URL || 'http://127.0.0.1:18080';
const browser = await chromium.launch({headless:true, args:['--no-sandbox']});
// Optional existing credentials file; never put secrets in argv, URLs or logs.
const credentials = process.env.ONLYCOIN_AUTH_FILE
  ? Object.fromEntries(readFileSync(process.env.ONLYCOIN_AUTH_FILE,'utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)])) : null;
const page = await browser.newPage(credentials ? {httpCredentials:{username:credentials.user,password:credentials.password}} : {});
try {
  await page.goto(`${base}/review?board=y`);
  await page.getByRole('button', {name:'OnlyCoin · 来源候选回放'}).click();
  const live = page.locator('[data-testid="onlycoin-live"]');
  await live.waitFor();
  await page.waitForFunction(() => document.querySelector('[data-testid="onlycoin-live"] .onlycoin-lists'));
  const api = await (await page.request.get(`${base}/api/v1/onlycoin/live`)).json();
  const symbols = await live.locator('.onlycoin-lists > div').nth(2).locator('li a').allTextContents();
  assert.deepEqual(symbols,api.symbols);
  const list = live.locator('.onlycoin-lists > div').nth(2).locator('ul');
  const geometry = await list.evaluate(el=>({height:el.clientHeight,scrollHeight:el.scrollHeight,overflow:getComputedStyle(el).overflowY}));
  assert.ok(geometry.height <= 200 && geometry.scrollHeight > geometry.height && geometry.overflow === 'auto');
  await list.locator('li').last().scrollIntoViewIfNeeded();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await live.locator('.onlycoin-lists > div').count(),3);
  await page.setViewportSize({width:1280,height:900});
  assert.equal(await page.getByLabel('UTC 业务日', {exact:true}).inputValue(),'');
  const revisions = [];
  page.on('response', r => { if (r.url().endsWith('/api/v1/onlycoin/live')) revisions.push(r.status()); });
  const date = page.getByLabel('UTC 业务日', {exact:true});
  await date.fill(api.business_date);
  await page.getByLabel('回放截至时间（本地 UTC+7）',{exact:true}).fill(`${api.business_date}T08:15`);
  const request = page.waitForRequest(r=>r.url().includes('/review/onlycoin?'));
  await page.getByRole('button',{name:'查询 / 刷新回放',exact:true}).click();
  const historyRequest = await request;
  assert.ok(historyRequest.url().includes('as_of=') && decodeURIComponent(historyRequest.url()).includes('T01:15:00Z'));
  assert.deepEqual(await live.locator('.onlycoin-lists > div').nth(2).locator('li a').allTextContents(),symbols);
  await page.waitForTimeout(16000);
  assert.ok(revisions.length >= 1, 'automatic poll must run');
  assert.equal(await date.inputValue(),api.business_date);
  const history = page.locator('.onlycoin-review-panel');
  await page.getByLabel('回放截至时间（本地 UTC+7）',{exact:true}).fill(`${api.business_date}T08:16`);
  await page.getByRole('button',{name:'查询 / 刷新回放',exact:true}).click();
  await history.locator('.onlycoin-lists').waitFor();
  assert.ok(await history.locator('.onlycoin-lists li a').count() > 0, 'populated history');
  const historicText = await history.innerText();
  await page.route('**/api/v1/onlycoin/live', route => route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({valid:false,error:'TEST_UNAVAILABLE'})}));
  await live.getByRole('button',{name:'刷新实时名单'}).click();
  await live.getByRole('alert').waitFor();
  assert.equal(await live.locator('li a').count(),0,'failed fetch must clear members');
  assert.equal(await history.innerText(),historicText,'live failure must not alter history');
  await page.unroute('**/api/v1/onlycoin/live');
  await live.getByRole('button',{name:'刷新实时名单'}).click();
  await live.locator('.onlycoin-lists').waitFor();
  const latest = await (await page.request.get(`${base}/api/v1/onlycoin/live`)).json();
  await page.route('**/api/v1/onlycoin/live', route => route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...latest,status:'empty',symbols:[],onlycoin:[],long:[],short:[],counts:{onlycoin:0,long:0,short:0}})}));
  await live.getByRole('button',{name:'刷新实时名单'}).click();
  await live.getByText('暂无成员',{exact:true}).first().waitFor();
  assert.equal(await live.locator('li a').count(),0);
  await page.unroute('**/api/v1/onlycoin/live');
  await page.route('**/api/v1/onlycoin/live', route => route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...latest,valid_until_utc:new Date(Date.parse(latest.server_time)+1200).toISOString()})}));
  await live.getByRole('button',{name:'刷新实时名单'}).click();
  await live.locator('.onlycoin-lists').waitFor();
  await live.getByText('实时来源已过期，旧成员已隐藏；等待更新。',{exact:true}).waitFor();
  assert.equal(await live.locator('li a').count(),0);
  await page.unroute('**/api/v1/onlycoin/live');
  const next = await (await page.request.get(`${base}/api/v1/onlycoin/live`)).json();
  await page.goto(`${base}/screener-y`);
  await page.waitForFunction(()=>document.querySelector('.onlycoin-panel .onlycoin-lists'));
  assert.deepEqual(await page.locator('.onlycoin-panel .onlycoin-lists > div').nth(2).locator('li a').allTextContents(),next.symbols);
  console.log(JSON.stringify({passed:true,symbols:symbols.length,revision:api.projection_revision,historicalRequest:historyRequest.url(),pollAndHistoryIsolation:true,crossPage:true,emptyErrorExpiryRecovery:true}));
} finally { await browser.close(); }
